services:
  - type: web
    name: turtleg-backend
    env: node
    rootDir: Backend
    branch: main
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
        sync: false

  - type: static_site
    name: turtleg-frontend
    env: node
    rootDir: Frontend
    branch: main
    plan: free
    buildCommand: npm ci --include=dev --silent && npm run build
    staticPublishPath: dist
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
        sync: false
      - key: NODE_OPTIONS
        value: "--max-old-space-size=3072"
        sync: false
